/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import tools.ColorChooserButton;

/**
 *
 * @author max
 */
public class ConfigurationFrame extends javax.swing.JFrame
{

    /**
     * Creates new form ConfigurationFrame
     */
    public ConfigurationFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ColorTextGeneral = new ColorChooserButton(new Color(0,255,0));
        ColorTextGeneral1 = new ColorChooserButton(new Color(0,255,0));
        jLabel3 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ColorTextGeneral2 = new ColorChooserButton(new Color(0,255,0));
        jLabel5 = new javax.swing.JLabel();
        ColorTextGeneral3 = new ColorChooserButton(new Color(0,255,0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Configracion General");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 46));

        jLabel2.setText("Color variables");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 46));

        ColorTextGeneral.setText("");
        ColorTextGeneral.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ColorTextGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        ColorTextGeneral1.setText("");
        ColorTextGeneral1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ColorTextGeneral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel3.setText("Color del texto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 46));

        closeButton.setText("close();");
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 170, 50));

        jLabel4.setText("Color fondo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 46));

        ColorTextGeneral2.setText("");
        ColorTextGeneral2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ColorTextGeneral2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLabel5.setText("Color variables");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 46));

        ColorTextGeneral3.setText("");
        ColorTextGeneral3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ColorTextGeneral3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private  ColorChooserButton generalColor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ColorTextGeneral;
    private javax.swing.JButton ColorTextGeneral1;
    private javax.swing.JButton ColorTextGeneral2;
    private javax.swing.JButton ColorTextGeneral3;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the closeButton
     */
    public javax.swing.JButton getCloseButton()
    {
        return closeButton;
    }
}
